"""
chaster/token_encryptor.py

TokenEncryptor -- the ONLY place in this codebase that touches
`cryptography.fernet`. Knows nothing about the database, Discord, or
any specific token's meaning -- a pure in-memory string transform.

Design (docs/architecture/chaster_integration_technical_design.md,
Section 10):
- Fernet (AES-128-CBC + HMAC-SHA256), never raw AES-GCM -- nonce
  generation and tamper detection are handled internally by Fernet,
  removing an entire class of hand-rolled-AEAD mistakes.
- The master key comes from deployment configuration (`Config`), never
  generated by this class -- a missing/invalid key fails fast, at
  construction, not silently at first use.
- `Fernet.decrypt()`'s own `ttl=` parameter is deliberately NEVER used
  here: it rejects a token based on a timestamp embedded at encryption
  time, which is meant for short-lived messages, not long-lived stored
  credentials. Token freshness for Chaster tokens is represented by
  this project's own explicit `access_token_expires_at`/
  `refresh_token_expires_at` columns (chaster/models.py), never by
  Fernet's own internal clock.
- Never logs, never includes plaintext/ciphertext in an exception
  message beyond what's already been raised by `cryptography` itself
  (which itself never echoes the input) -- see this module's own
  tests for a captured-log/exception-text assertion proving this.
"""

from __future__ import annotations

from cryptography.fernet import Fernet, InvalidToken


class TokenEncryptorConfigurationError(ValueError):
    """Raised at construction time when the supplied master key is
    missing or is not a valid Fernet key -- never at first use. A
    misconfigured deployment must fail loudly and immediately, not
    silently accept requests it cannot actually protect."""


class TokenDecryptionError(ValueError):
    """Raised when a stored ciphertext cannot be decrypted -- wrong
    key, corrupted/tampered data, or a malformed payload. Never
    includes the ciphertext or any decrypted fragment in its own
    message; callers should reference a connection_id or similar,
    never the token material itself."""


class TokenEncryptor:
    """Encrypts/decrypts short string tokens (Chaster OAuth access and
    refresh tokens) for storage as plain TEXT. Every plaintext value
    passed to `encrypt()` and returned by `decrypt()` is a `str` --
    never bytes -- so callers never need their own encoding logic."""

    def __init__(self, master_key: str | bytes | None) -> None:
        if not master_key:
            raise TokenEncryptorConfigurationError(
                "CHASTER_TOKEN_ENCRYPTION_KEY is not set. A Chaster connection "
                "cannot be encrypted or decrypted without a configured master key. "
                "Generate one with: python3 -c \"from cryptography.fernet import "
                "Fernet; print(Fernet.generate_key().decode())\" -- then set it in "
                ".env. This key is never generated automatically by the "
                "application, and once real connections exist, it must be backed "
                "up separately from the database (see .env.example)."
            )
        try:
            self._fernet = Fernet(master_key)
        except Exception as exc:
            # cryptography raises a bare ValueError for a malformed key
            # (wrong length/not valid base64) -- re-raised under our own
            # specific type so callers can catch it, without ever
            # including the (invalid) key value itself in the message.
            raise TokenEncryptorConfigurationError(
                "CHASTER_TOKEN_ENCRYPTION_KEY is set but is not a valid Fernet "
                "key (expected the exact output of Fernet.generate_key())."
            ) from exc

    def encrypt(self, plaintext: str) -> str:
        """Encrypts a plaintext token. Rejects an empty/whitespace-only
        value -- mirroring this project's own established
        empty-string-rejection convention elsewhere (Candidate B's
        title/instructions validation) -- since an "encrypted empty
        string" is never a meaningful stored credential."""
        if not isinstance(plaintext, str):
            raise TypeError(f"plaintext must be str, got {type(plaintext).__name__}")
        if not plaintext.strip():
            raise ValueError("plaintext token must not be empty or whitespace-only.")
        token = self._fernet.encrypt(plaintext.encode("utf-8"))
        return token.decode("ascii")  # a Fernet token is already URL-safe base64 ASCII

    def decrypt(self, ciphertext: str) -> str:
        """Decrypts a previously-encrypted token. Raises
        TokenDecryptionError -- never the raw `cryptography.fernet.
        InvalidToken` -- on any failure (wrong key, corrupted/tampered
        ciphertext, or a malformed payload); this project's own
        convention is specific, named exception types, not letting a
        third-party library's own exception type leak through call
        boundaries. Deliberately does NOT pass `ttl=` -- see this
        module's own docstring."""
        if not isinstance(ciphertext, str):
            raise TypeError(f"ciphertext must be str, got {type(ciphertext).__name__}")
        try:
            plaintext = self._fernet.decrypt(ciphertext.encode("ascii"))
        except InvalidToken as exc:
            raise TokenDecryptionError(
                "Stored token could not be decrypted -- wrong encryption key, "
                "corrupted data, or a malformed payload."
            ) from exc
        except (ValueError, TypeError) as exc:
            # A ciphertext that isn't even valid base64/ASCII raises here,
            # before Fernet's own InvalidToken check is reached.
            raise TokenDecryptionError(
                "Stored token could not be decrypted -- the stored value is not "
                "a valid Fernet token."
            ) from exc
        return plaintext.decode("utf-8")
